### ISSUE TITLE
hiding different portions of a post, while keeping others visible

### ISSUE THREAD

**Issue by ZouBCivil** [andrezrv/hide-this#2]
Hi,

I'm using this plugin and it is great.

I am having some difficulty in trying to show a paragraph between 2 hidden sections of a post.
..........
Unhidden paragraph 1
[hide] some hidden content [/hide]
Unhidden paragraph 2
[hide] some more hidden content [/hide]
...........

In the case above, Unhidden paragraph 2 is still hidden, I am guessing because it is within the second [/hide]

Am I right to assume this.  Is there a fix for this?

Thanks,

Zou

**Comment by andrezrv** [comment]
Are you adding that content in the advanced editor or the plain text mode? Sometimes the editor messes up the HTML format, and when using shortcodes you need to add extra line breaks in order for them to work properly.
